language: java
jdk:
- oraclejdk8
env:
  global:
    secure: dDk7l8qEPLqqkoVlUfBSMbEoWKOhlsJOwseE7EFx3VQQcw7KbGZZLAA6FU+IbRD/zpQZbelz2jMNwSwqhdrY5fokhWQAZcRtoqOUY2w+2+1JdiC/G2CFm1dexO0NUIajdQzU36INSdfKOkMjWxp5Akmuw4KCHG25PEizphyV2vI=
addons:
  coverity_scan:
    project:
      name: ElfoLiNk/weather-calendar
      version: 1.2-SNAPSHOT
      description: A university project for Software Engineering 2 on Weather based social Calendar
    notification_email: matteo_gazzetta@hotmail.it
    build_command_prepend: mvn clean
    build_command: mvn install
    branch_pattern: master
